[package]
name = "ip_sniffer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
